# Generated by Django 4.0.5 on 2022-07-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='specs')),
            ],
        ),
    ]
